### PR TITLE
add v0.6.0-alpine with multi-stage build

### PR DESCRIPTION
**Pull request by Kayuii**

### CODE REVIEW

**Comment by mpugach** [comment]
@Kayuii thank you. Is it ready?

**Review by mpugach — CHANGES_REQUESTED** [review]
please update the `## Tags` section of the Readme also

**Comment by Kayuii** [comment]
> @Kayuii thank you. Is it ready?
yes, I built and used it in my dockerhub

**Review by mpugach — APPROVED** [review]

**Comment by mpugach** [comment]
👍

**Pull request merged**
